#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Debajit Adhikary <debajit@debajit.com>
#

[[ -f $HOME/.zshrc.local ]] && source $HOME/.zshrc.local          # Local config
[[ -f $HOME/.aliases ]] && source $HOME/.aliases                  # General aliases
[[ -f $HOME/.aliases.local ]] && source $HOME/.aliases.local      # Local aliases

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Prompt
prompt debajit

# Customize to your needs...
export PATH="$PATH:$HOME/.mix/escripts" # Add Mix escripts to PATH
