#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Debajit Adhikary <debajit@debajit.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[[ -f $HOME/.zsh_aliases ]] && source $HOME/.zsh_aliases  # Custom aliases
[[ -f $HOME/.zshrc.local ]] && source ~/.zshrc.local      # Local config

# Customize to your needs...
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
